version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - mysql
    container_name: mta-hosting-web
    environment:
      - 'DB_PORT=3306'
      - 'DB_HOST=mysql'

  # database:
  #   image: mysql:5.7.22
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: root
  #     MYSQL_DATABASE: golang-docker
  #   container_name: golang-docker-db
  #   ports:
  #     - 33066:3306
  #   volumes:
  #     - golang-docker-data:/var/lib/mysql 

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./docker/.env
    ports:
      - 33066:3306
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - 5003:80
    environment:
      - 'PMA_HOST=mysql'
      - 'PMA_PORT=3306'
    container_name: mta-hosting-pma

networks:
  internal:
    driver: bridge

# persisted storage
volumes:
  db-data: