name: "Multiple Operations"

on:
  workflow_dispatch:
    inputs:
      kafka_env:
        type: choice
        description: 'Kafka environment to create the topic.'
        required: true
        default: 'staging'
        options:
        - 'staging'
        - 'production'
      topic_name:
        description: Topic Name (It must be specified in valid JSON format.)
        required: true
      file_path:
        description: File name with path.
        required: true

env:
  KAFKA_ENV: "${{ github.event.inputs.kafka_env }}"
  TOPIC_NAME: "${{ github.event.inputs.topic_name }}"
  TOPIC_PATH: "${{ github.event.inputs.file_path }}"

jobs:
  kafka-api:
    name: "Kafka Topic Creation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: set_var
        run: |
          content=`cat ./${{ github.event.inputs.file_path }}`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: use inputs and filter topic
        run: |
           echo "`jq '.${{ env.TOPIC_NAME }}' ./${{ env.TOPIC_PATH }}`" > config.json
      - run: |
          if [[ -f "config.json" && -s "config.json" ]]; then 
            ENV=${{ env.KAFKA_ENV  }}
            if [[ $ENV == "production" ]]; then
                URL="https://kafka-api.51b.tech"
            fi
            if [[ $ENV == "staging" ]]; then
                URL="https://reqres.in/api/users"
            fi
            curl -d @config.json -H 'Content-Type: application/json'  $URL
          fi
          echo "Check logs"
